# Generated by Django 4.1.1 on 2022-09-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=200, null=True)),
                ('decendants', models.CharField(blank=True, max_length=200, null=True)),
                ('storyid', models.CharField(blank=True, max_length=150, null=True)),
                ('score', models.CharField(blank=True, max_length=200, null=True)),
                ('storytime', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.TextField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
