# Generated by Django 4.1.1 on 2022-09-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
