# Generated by Django 4.1.1 on 2022-09-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0002_stories_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='kids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
