# Generated by Django 4.1.1 on 2022-09-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0004_remove_stories_kids_remove_stories_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=150, null=True)),
                ('decendants', models.CharField(blank=True, max_length=150, null=True)),
                ('askId', models.CharField(blank=True, max_length=150, null=True)),
                ('kids', models.JSONField()),
                ('score', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=150, null=True)),
                ('jobIds', models.CharField(blank=True, max_length=150, null=True)),
                ('score', models.CharField(blank=True, max_length=150, null=True)),
                ('time', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
