# Generated by Django 4.1.1 on 2022-09-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0006_remove_jobstories_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askstories',
            name='kids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
