# Generated by Django 4.1.1 on 2022-09-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0007_alter_askstories_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='askstories',
            name='source',
            field=models.CharField(blank=True, choices=[('Hackernews', 'Hackernews'), ('User', 'User')], default='Hackernews', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobstories',
            name='source',
            field=models.CharField(blank=True, choices=[('Hackernews', 'Hackernews'), ('User', 'User')], default='Hackernews', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stories',
            name='source',
            field=models.CharField(blank=True, choices=[('Hackernews', 'Hackernews'), ('User', 'User')], default='Hackernews', max_length=100, null=True),
        ),
    ]
