# Generated by Django 4.1.1 on 2022-09-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnapp', '0008_askstories_source_jobstories_source_stories_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='source',
            field=models.CharField(choices=[('Hackernews', 'Hackernews'), ('User', 'User')], default='Hackernews', max_length=100),
        ),
    ]
